package pacote;

import javax.swing.JOptionPane;

/**
 *
 * @author joao
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrpCor = new javax.swing.ButtonGroup();
        GrpAvatar = new javax.swing.ButtonGroup();
        LblCor = new javax.swing.JLabel();
        TxtNick = new javax.swing.JTextField();
        LblNick = new javax.swing.JLabel();
        RadAzul = new javax.swing.JRadioButton();
        RadVerde = new javax.swing.JRadioButton();
        RadVermelho = new javax.swing.JRadioButton();
        LblAvatar = new javax.swing.JLabel();
        RadAvatar1 = new javax.swing.JRadioButton();
        LblAvatar1 = new javax.swing.JLabel();
        RadAvatar2 = new javax.swing.JRadioButton();
        LblAvatar2 = new javax.swing.JLabel();
        RadAvatar3 = new javax.swing.JRadioButton();
        LblAvatar3 = new javax.swing.JLabel();
        BtnEntrar = new javax.swing.JButton();
        LblServidor = new javax.swing.JLabel();
        TxtServidor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(420, 270));
        setName("FrmLogin"); // NOI18N
        getContentPane().setLayout(null);

        LblCor.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LblCor.setText("Cor:");
        getContentPane().add(LblCor);
        LblCor.setBounds(60, 50, 50, 40);

        TxtNick.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        getContentPane().add(TxtNick);
        TxtNick.setBounds(110, 10, 280, 30);

        LblNick.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LblNick.setText("Nickname:");
        getContentPane().add(LblNick);
        LblNick.setBounds(10, 10, 130, 40);

        GrpCor.add(RadAzul);
        RadAzul.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        RadAzul.setForeground(new java.awt.Color(0, 0, 102));
        RadAzul.setSelected(true);
        RadAzul.setText("Azul");
        RadAzul.addActionListener(this::RadAzulActionPerformed);
        getContentPane().add(RadAzul);
        RadAzul.setBounds(110, 60, 60, 22);

        GrpCor.add(RadVerde);
        RadVerde.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        RadVerde.setForeground(new java.awt.Color(0, 153, 0));
        RadVerde.setText("Verde");
        RadVerde.addActionListener(this::RadVerdeActionPerformed);
        getContentPane().add(RadVerde);
        RadVerde.setBounds(170, 60, 70, 22);

        GrpCor.add(RadVermelho);
        RadVermelho.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        RadVermelho.setForeground(new java.awt.Color(255, 0, 0));
        RadVermelho.setText("Vermelho");
        RadVermelho.addActionListener(this::RadVermelhoActionPerformed);
        getContentPane().add(RadVermelho);
        RadVermelho.setBounds(240, 60, 100, 22);

        LblAvatar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LblAvatar.setText("Avatar:");
        getContentPane().add(LblAvatar);
        LblAvatar.setBounds(40, 90, 70, 22);

        GrpAvatar.add(RadAvatar1);
        RadAvatar1.setSelected(true);
        RadAvatar1.addActionListener(this::RadAvatar1ActionPerformed);
        getContentPane().add(RadAvatar1);
        RadAvatar1.setBounds(110, 90, 19, 19);

        LblAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-lanterna-verde-16.png"))); // NOI18N
        LblAvatar1.setLabelFor(RadAvatar1);
        getContentPane().add(LblAvatar1);
        LblAvatar1.setBounds(130, 90, 20, 20);

        GrpAvatar.add(RadAvatar2);
        RadAvatar2.addActionListener(this::RadAvatar2ActionPerformed);
        getContentPane().add(RadAvatar2);
        RadAvatar2.setBounds(160, 90, 19, 19);

        LblAvatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-the-flash-sign-16.png"))); // NOI18N
        LblAvatar2.setLabelFor(RadAvatar2);
        getContentPane().add(LblAvatar2);
        LblAvatar2.setBounds(180, 90, 20, 20);

        GrpAvatar.add(RadAvatar3);
        RadAvatar3.addActionListener(this::RadAvatar3ActionPerformed);
        getContentPane().add(RadAvatar3);
        RadAvatar3.setBounds(210, 90, 19, 19);

        LblAvatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-batman-antigo-16.png"))); // NOI18N
        LblAvatar3.setLabelFor(RadAvatar3);
        getContentPane().add(LblAvatar3);
        LblAvatar3.setBounds(230, 90, 20, 20);

        LblServidor.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        LblServidor.setText("Servidor:");
        getContentPane().add(LblServidor);
        LblServidor.setBounds(20, 125, 90, 30);

        TxtServidor.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        TxtServidor.setText(Util.ServidorIP);
        TxtServidor.setToolTipText("IP da máquina que está rodando o Chat_Middleware_Service");
        getContentPane().add(TxtServidor);
        TxtServidor.setBounds(110, 125, 280, 30);

        BtnEntrar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        BtnEntrar.setText("ENTRAR");
        BtnEntrar.addActionListener(this::BtnEntrarActionPerformed);
        getContentPane().add(BtnEntrar);
        BtnEntrar.setBounds(110, 170, 170, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadAzulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadAzulActionPerformed

    private void RadVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadVerdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadVerdeActionPerformed

    private void RadVermelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadVermelhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadVermelhoActionPerformed

    private void RadAvatar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadAvatar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadAvatar1ActionPerformed

    private void RadAvatar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadAvatar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadAvatar2ActionPerformed

    private void RadAvatar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadAvatar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadAvatar3ActionPerformed

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
        if (!TxtNick.getText().equals("")){
            Util.nickname = TxtNick.getText();
            if (!TxtServidor.getText().isBlank()) {
                Util.ServidorIP = TxtServidor.getText().trim();
            }
            if(RadAzul.isSelected()){
                Util.cor = "Blue";
            } else if (RadVerde.isSelected()){
                Util.cor = "Green";
            } else if (RadVermelho.isSelected()) {
                Util.cor = "Red";
            }
            if(RadAvatar1.isSelected()){
                Util.avatar = "icons8-lanterna-verde-16.png";
            } else if(RadAvatar2.isSelected()){
                Util.avatar = "icons8-the-flash-sign-16.png";
            } else if(RadAvatar3.isSelected()){
                Util.avatar = "icons8-batman-antigo-16.png";
            }
            FrmChat frmchat = new FrmChat();
            frmchat.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null,"Digite um Nickname!");
        }
    }//GEN-LAST:event_BtnEntrarActionPerformed

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEntrar;
    private javax.swing.ButtonGroup GrpAvatar;
    private javax.swing.ButtonGroup GrpCor;
    private javax.swing.JLabel LblAvatar;
    private javax.swing.JLabel LblAvatar1;
    private javax.swing.JLabel LblAvatar2;
    private javax.swing.JLabel LblAvatar3;
    private javax.swing.JLabel LblCor;
    private javax.swing.JLabel LblNick;
    private javax.swing.JLabel LblServidor;
    private javax.swing.JRadioButton RadAvatar1;
    private javax.swing.JRadioButton RadAvatar2;
    private javax.swing.JRadioButton RadAvatar3;
    private javax.swing.JRadioButton RadAzul;
    private javax.swing.JRadioButton RadVerde;
    private javax.swing.JRadioButton RadVermelho;
    private javax.swing.JTextField TxtNick;
    private javax.swing.JTextField TxtServidor;
    // End of variables declaration//GEN-END:variables
}
